; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
custom_fw_version = 2_2
framework = arduino
monitor_speed = 115200
platform = espressif32

[common]
build_flags = 
	-D TYPE_BW
	-D D_GDEW0154T8
lib_deps_builtin = 
lib_deps = 

[env:epdiy_v7]
board = epdiy_v7
build_flags = 
	${common.build_flags}
	-D D_FASTEPD
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=0
lib_deps = 
	${common.lib_deps_builtin}
	${common.lib_deps}
	bitbank2/FastEPD@^1.2.0
	bitbank2/PNGdec@^1.1.0
	madhephaestus/ESP32AnalogRead@^0.3.0
